baseURL = 'https://jehapedia.org/'
languageCode = 'ar'
title = 'جِحَابيديا'
theme = 'alf-layla'
defaultContentLanguage = 'ar'
enableRobotsTXT = false

[params]
  description = 'موسوعة نوادر جحا'
  descriptionEn = 'Encyclopedia of Juha Tales'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 12

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[outputFormats]
  [outputFormats.RSS]
    mediaType = 'application/rss+xml'
    baseName = 'feed'
